Vagrant.configure("2") do |config|

  config.vm.synced_folder ".", "/vagrant"   

  config.vm.provision "shell", inline: <<-SHELL
    yum install -y https://repo.percona.com/yum/percona-release-latest.noarch.rpm
    yum install -y Percona-Server-server-57
    SHELL


  config.vm.define "master" do |master|
    master.vm.box = "centos/7"
    master.vm.host_name = 'master'  
    master.vm.network :private_network, ip: "192.168.57.11"

    master.vm.provider "virtualbox" do |vbx|
      vbx.memory = "512"
      vbx.cpus = "1"
        vbx.customize ["modifyvm", :id, '--audio', 'none']
    end     
  end

  config.vm.define "slave" do |slave|
    slave.vm.box = "centos/7"
    slave.vm.host_name = 'slave'  
    slave.vm.network :private_network, ip: "192.168.57.12"

    slave.vm.provider "virtualbox" do |vbx|
      vbx.memory = "512"
      vbx.cpus = "1"
      vbx.customize ["modifyvm", :id, '--audio', 'none']
    end     
  end
end
