# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"

    config.vm.provider "virtualbox" do |v|
        v.memory = 200
        v.cpus = 1
    end

       
    config.vm.define "web" do |web|
        web.vm.network "private_network", ip: "192.168.56.10"
        web.vm.hostname = "web"
        web.vm.network "forwarded_port", guest: 80, host: 80
    end 
    
    
    config.vm.define "log" do |log|
        log.vm.network "private_network", ip: "192.168.56.15"
        log.vm.hostname = "log"
    end  

    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "playbook.yml"
        ansible.become = true
        ansible.limit = "all"
        ansible.host_key_checking = "false"        
        ansible.groups = {
          "webservers" => ["web"],
          "rsyslogservers" => ["log"],
        }     
    end    
end
