# -*- mode: ruby -*-
# vim: set ft=ruby :
MACHINES = {
  :web => {
        :config => "centos/7",
        :ip_addr => '192.168.56.10'
  },
  :log => {
        :config => "centos/7",
        :ip_addr => '192.168.56.15'
  },
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:config]
          box.vm.host_name = boxname.to_s

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "200"]
      end
    end 	
  end
end
